version: "3"
services:
  chat-postgres-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - 5432:5432
    networks:
      - webnet
  chat-backend:
    environment:
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    working_dir: "/chat-backend"
    command: mvn clean spring-boot:run
    volumes:
      - ./chat-backend:/chat-backend
    depends_on:
      - chat-postgres-db
    ports:
      - 8080:8080
    networks:
      - webnet
  chat-frontend:
    ports:
      - 3000:3000
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URI=${REACT_APP_BACKEND_URI}
        - REACT_APP_BACKEND_WS_URI=${REACT_APP_BACKEND_WS_URI}
    depends_on:
      - chat-backend
    networks:
      - webnet
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - 5050:5050
    networks:
      - webnet
networks:
  webnet:
